Tomtseng/suppress pass alive
HumanCompatibleAI/KataGo-custom pull request #61
Opened 2022-11-02 06:00 UTC by tomtseng

```
/engines/KataGo-custom/cpp/search/searchresults.cpp: In member function 'bool Search::getPlaySelectionValues(const SearchNode&, std::vector<short int>&, std::vector<double>&, std::vector<double>*, double, bool, bool, bool, double*, double*) const':
/engines/KataGo-custom/cpp/search/searchresults.cpp:79:9: warning: ISO C++ forbids variable length array 'territories' [-Wvla]
   79 |   Color territories[suppressPassAliveTerritory ? Board::MAX_ARR_SIZE : 0];
      |         ^~~~~~~~~~~
```

2022-11-29 22:28 UTC, ed1d1a8d requested changes
Sorry for taking so long to get around to this.

Overall a really comprehensive PR, thanks for running all the tests to cross-check that this doesn't break anything. Also the fact that we got our circler-adversary working against this PR is strong evidence that it works.

Just had one requested change to handle what I think is an edge case we don't currently cover.

2022-11-29 22:28 UTC, ed1d1a8d commented on cpp/search/searchresults.cpp
> +        const bool isSuppressedMove = (suppressPass && moveLoc == Board::PASS_LOC)
I think there is a potential failure mode here where there are legal moves outside of {passing, pass-alive territory}, but our NN assigns near zero probability (i.e. < 1e-50) to those moves (maybe because it was trained poorly). In this case we would return no legal moves and I think KataGo will crash. Maybe we can adjust the logic so that if there are literally no legal moves, we default to passing?

It'd be nice if we could add a test for this case as well.

Let me know if this makes sense or I am just being mistakenly paranoid.

2022-12-06 06:40 UTC, tomtseng commented on cpp/search/searchresults.cpp
> +        const bool isSuppressedMove = (suppressPass && moveLoc == Board::PASS_LOC)
In practice this hasn't been an issue — our hardened training run hasn't crashed due to this.

TBH not sure how to run KataGo tests but I've added some logic to handle the failure mode

2022-12-14 03:13 UTC, AdamGleave commented
> TBH not sure how to run KataGo tests but I've added some logic to handle the failure mode

The TL;DR is to run the scripts in `engines/KataGo-custom/cpp/run*tests*.sh` and then do a `git diff` of the output. However, @norabelrose has found some anomalies here even on our stable branch, so worth syncing up with her.

@ed1d1a8d are you OK handling the re-review? Let me know if there's anything you'd like me to take a look at.

2022-12-14 19:50 UTC, norabelrose approved these changes
This looks good to me, I just ran `runsearchtests.sh` and there's no diff in the output relative to `stable`.

2022-12-14 20:34 UTC, ed1d1a8d commented on cpp/search/searchresults.cpp
> +  if(maxUnsuppressedChildWeight == 0.0) {
Should we compute `maxUnsuppressedChildWeight` right before this check?

My motivations:
1. It makes the code clearer. We don't have to think about `maxUnsuppressedChildWeight` as we are reading code until right before we need it.
2. We actually modify `playSelectionValues` even after `maxUnsuppressedChildWeight` is computed. So `maxUnsuppressedChildWeight` is actually some weird stale value.

Finally, what do you think about renaming `maxUnsuppressedChildWeight` to `maxPlaySelectionValue`?

2022-12-14 20:36 UTC, ed1d1a8d commented on cpp/search/searchresults.cpp
> +    const bool isSuppressedMove = (suppressPass && moveLoc == Board::PASS_LOC)
Could we refactor this out into a helper lambda function? We have it written in three different places and I think it would be less error prone if we didn't repeat ourselves.

2022-12-14 20:37 UTC, ed1d1a8d requested changes
The fallback pass option looks good.

Just requested a few more small refactors to make things cleaner and less error prone.

I might actually take a shot at writing up a small test of this myself.

2022-12-15 05:15 UTC, tomtseng commented
Addressed comments. If you don't end up having time to write a test then I'll invest some time in figuring out how to run/write tests

2022-12-16 01:36 UTC, ed1d1a8d commented
> Addressed comments
LGTM!

> If you don't end up having time to write a test then I'll invest some time in figuring out how to run/write tests
I added some tests and they will fail if we don't have the extra failure mode logic you added. If the tests look good to you am fine with merging.

2022-12-16 01:36 UTC, ed1d1a8d approved these changes

2022-12-16 01:37 UTC, ed1d1a8d commented on cpp/main.cpp
> +runexpensivetests : Expensive tests (mostly for the go_attack project).
Just cleaning up documentation here.

2022-12-19 08:26 UTC, merged