search: Allow both bots to use AMCTS
HumanCompatibleAI/KataGo-custom pull request #82
Opened 2023-02-24 02:58 UTC by tomtseng

The assertion `assert(!oppParams.usingAdversarialAlgo())` fails when two AMCTS bots play against each other. We should allow AMCTS bots to play as long as they're not doing recursive modeling.

2023-03-03 06:14 UTC, ed1d1a8d commented on cpp/search/search.cpp
> +      // we'll have infinite recursion.
Reminds me of https://acritch.com/osgt-is-weird/.

2023-03-03 06:15 UTC, ed1d1a8d commented on cpp/search/search.cpp
> +      assert(oppNNEval != nullptr);
```suggestion
      assert(oppNNEval != nullptr);
      
```
Just adding a space afterwards to group related logic to make things easier to read.

2023-03-03 06:22 UTC, ed1d1a8d commented on cpp/search/search.cpp
> +      SearchParams oppOppParams = oppParams.usingAdversarialAlgo() ? searchParams : SearchParams();
Is this necessary?

Per https://github.com/AlignmentResearch/KataGo-custom/blob/e4451f7d5bde8d1a252ac13e3ac66225d0bd242a/cpp/search/search.h#L391-L398, this line only has an effect if oppParams.usingAdversarialAlgo() is true. But if oppParams.usingAdversarialAlgo() is true, the assert above guarantees `oppParams.maxVisits == 1`, which means it doesn't matter what we set as oppOppParams?

2023-03-03 06:24 UTC, ed1d1a8d requested changes
Short PR but surprisingly tricky logic.
Left just one comment -- could you drop one of the lines of logic?

2023-03-03 09:22 UTC, tomtseng commented on cpp/search/search.cpp
> +      SearchParams oppOppParams = oppParams.usingAdversarialAlgo() ? searchParams : SearchParams();
good point, we can remove this — I had added this line before adding the surrounding `if` block that makes this unnecessary

2023-03-06 04:00 UTC, ed1d1a8d approved these changes
LGTM!

2023-03-07 20:15 UTC, merged