Merge v1.12.0
HumanCompatibleAI/KataGo-custom pull request #89
Opened 2023-05-14 07:58 UTC by tomtseng

Biggest merge conflict is that `train.py` has been rewritten to not use TF, so most of our `train.py` changes got discarded except for the `disable-vtimeloss`.

TODO: warmstarting setup needs to be changed (for `train.py`, specify `-model-kind` if not warmstarting, and specify `-initial-checkpoint` if warmstarting. But how do I convert from our old TF checkpoints to a Pytorch checkpoint?)

2023-05-15 03:29 UTC, ed1d1a8d requested changes
Have checked over all non python/* files. Since the pytorch code seems to be non backwards compatible with the tensorflow code (per lightvector's checkpoint comments), I'm thinking we just copy over the python/* files exactly as is from the v1.12 code. If we need to finetune an older network, we just use an older version of the repo.

2023-05-15 03:29 UTC, ed1d1a8d commented on cpp/tests/testamcts.cpp
> +      double exploreScaling = bot.getExploreScaling(totalChildWeight, parentUtilityStdevFactor);
```suggestion
      const double exploreScaling = bot.getExploreScaling(totalChildWeight, parentUtilityStdevFactor);
```

2023-05-15 03:29 UTC, ed1d1a8d commented on cpp/tests/testamcts.cpp
> +    double exploreScaling = bot.getExploreScaling(totalChildWeight, 1.0);
```suggestion
    const double exploreScaling = bot.getExploreScaling(totalChildWeight, 1.0);
```

2023-05-15 07:36 UTC, tomtseng commented
(Context to make this conversation clearer to others: We now cannot warmstart from old <=v1.11 models since they're saved as TF checkpoints whereas v1.12.0 has switched to PyTorch and expects PyTorch checkpoints. I asked on Discord whether there was a nice way to convert from TF checkpoints to PyTorch checkpoints and lightvector said there's no official way. Someone else suggested trying [MMdnn](https://github.com/Microsoft/MMdnn) for conversion.)

The Python files were essentially just copied over except for `-disable-vtimeloss` plus some changes to make the Python linter happy. If we don't think we'll care about `-disable-vtimeloss` for finetuning the newer KataGo architectures then yeah, let's just copy the v1.12.0 Python code without changes and disable linting for those files. 
I think removing `-disable-vtimeloss` is fine — the newer KataGo architectures were all trained with vtimeloss and it seems consistent to finetune them with vtimeloss as well. But we used `-disable-vtimeloss` for training our adversaries, and we might care about that eventually (e.g., if we work on adding vision transformers and think it's easier to write them in PyTorch instead of TF).

It does seem like converting checkpoints from TF to PyTorch will take some effort and it's risky to devote time to it right now. 
I think I'll add another copy of KataGo in `/go_attack/engines` that has the old TF training code, since we'll be using it frequently. In particular, whenever we want to finetune our cyclic adversary, we're using its TF checkpoint. I'll spend today setting up a finetuning run of the cyclic adversary vs. a b18c384nbt net and see if anything breaks.

2023-08-10 22:12 UTC, ed1d1a8d commented
I'd actually vote the leave out vtimeloss completely. We can make a commit to add it back in once we start running experiments that actually require disabling vtimeloss. I'm afraid of adding it back in right now without proper testing.

2023-08-23 07:19 UTC, tomtseng commented
OK, I removed the `-disable-vtimeloss` flag and made a draft PR in case we want to add the flag back in: https://github.com/AlignmentResearch/KataGo-custom/pull/98

In the corresponding `go_attack` PR https://github.com/AlignmentResearch/go_attack/pull/118 I made the old TF training code a separate submodule. I think I like this a little more because it preserves the Git history of the TF training files (easier to Git Blame)

2023-11-20 02:23 UTC, ed1d1a8d approved these changes
Basically lgtm.

One clarification question -- I saw that `python/train.py` had number of changes compared to upstream. I'm guessing most of these were done to make linting pass? If so then this is good to merge IMO. If not then maybe we should revert the changes to make the file to match upstream more...

2024-03-02 05:46 UTC, merged